// <auto-generated />
using Conference.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conference.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230514143615_Initial migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Conference.Api.Models.WeatherForecastSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecastSummaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Summary = "Freezing"
                        },
                        new
                        {
                            Id = 2,
                            Summary = "Bracing"
                        },
                        new
                        {
                            Id = 3,
                            Summary = "Chilly"
                        },
                        new
                        {
                            Id = 4,
                            Summary = "Cool"
                        },
                        new
                        {
                            Id = 5,
                            Summary = "Mild"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
